jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

server:
  port: 8080

spring:
  application:
    name: stock-flow
  datasource:
    url: jdbc:postgresql://localhost:5432/db_stock_flow
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  web:
    resources:
      static-locations: classpath:/static/